"""All prompts used by the ontology TBox pipeline."""

from service.ontology_tbox_pipeline.prompts.extraction_prompts import (
    CLASS_EXTRACTION_SYSTEM_PROMPT,
    CLASS_EXTRACTION_USER_PROMPT,
    DATA_PROPERTY_EXTRACTION_SYSTEM_PROMPT,
    DATA_PROPERTY_EXTRACTION_USER_PROMPT,
    OBJECT_PROPERTY_EXTRACTION_SYSTEM_PROMPT,
    OBJECT_PROPERTY_EXTRACTION_USER_PROMPT,
)

__all__ = [
    "CLASS_EXTRACTION_SYSTEM_PROMPT",
    "CLASS_EXTRACTION_USER_PROMPT",
    "DATA_PROPERTY_EXTRACTION_SYSTEM_PROMPT",
    "DATA_PROPERTY_EXTRACTION_USER_PROMPT",
    "OBJECT_PROPERTY_EXTRACTION_SYSTEM_PROMPT",
    "OBJECT_PROPERTY_EXTRACTION_USER_PROMPT",
]

